### PR TITLE
Issue 99: Moved docs to /docs, updated GHA

### PR DESCRIPTION
**Pull request by joewxboy**
Signed-off-by: Joe Pearson <joewxboy@users.noreply.github.com>

Created new /docs folder, copied docs to it, linked previous docs to new docs, and added new GHA to auto-push to documentation site.

### CODE REVIEW

**Comment by joewxboy** [comment]
Note: I have not removed the older files and GHA yet until we prove that this approach works.

**Comment by joewxboy** [comment]
The `anaxdocscopy` GHA appears to be failing since the `devops/docs` folder does not _yet_ exist (and won't until this PR is merged).

**Review by johnwalicki — APPROVED** [review]
Thanks for the investigation  - approved

**Review by johnwalicki — DISMISSED** [review]
Hope this copy docs finally works!

**Comment by joewxboy** [comment]
Sorry, @johnwalicki I made one small update and that fixed the GHA I believe.  I need an approving review again before merging.

**Review by johnwalicki — APPROVED** [review]
All good!

**Pull request merged**
