### PR TITLE
generateToken() fix for macOS Big Sur

### PR DESCRIPTION
**Pull request by janvda**
Fixes issue : https://github.com/open-horizon/devops/issues/28

### CODE REVIEW

**Review by bmpotter — COMMENTED** [review]
Issue #28 indicated you also tested this on raspbian and centos. Please also test on ubuntu (or tell me that you did already). Thx!

**Comment by janvda** [comment]
I didn't test this on ubuntu as I don't have an ubuntu environment.

I think that the one line change can be easily tested on ubuntu by running the below command from the command line:
```
 head -c 1024 /dev/urandom | base64 | tr -cd A-Za-z0-9  | head -c 30;
```

FYI here below the line I have changed:
```
# based on https://gist.github.com/earthgecko/3089509#gistcomment-3530978 (also works on macOS Big Sur )
generateToken() { head -c 1024 /dev/urandom | base64 | tr -cd A-Za-z0-9  | head -c $1;}
```

**Review by bmpotter — APPROVED** [review]

**Review by bmpotter — CHANGES_REQUESTED** [review]
This PR is failing the DCO (sign-off) check. When you `git commit` your changes in your local repo, you need to use the `-s` flag. When this commit is pushed, the PR comment will have a string like `Signed-off-by: Antonii Sirotsinskyi asiro@softserveinc.com` in its comment.

**Comment by bmpotter** [comment]
Closing this PR, because i fixed this bug in https://github.com/open-horizon/devops/pull/52

**Pull request closed without merging**
