### PR TITLE
Changes: added WSL installation instructions for review

### PR DESCRIPTION
**Pull request by Demopans**
Added draft instructions to install both the management hub and agent for WSL2 for development purposes

### CODE REVIEW

**Comment by johnwalicki** [comment]
@TheMosquito   Can you take a look at this PR?

**Comment by TheMosquito** [comment]
@johnwalicki Yes. I am looking at it. I have verified that the procedures @Demopans has described here work to deploy both the all-in-one **Management Hub** and (separately) the **Agent** but I think some rewording would help make this stuff clearer for others to try. So I will be proposing some minor changes but I haven't had time to do that yet.

**Comment by TheMosquito** [comment]
@Demopans after weeks have gone by on this I decided that it would just be too difficult to modify your existing PR so instead I created a new PR with your content, here:  https://github.com/open-horizon/devops/pull/113
I would appreciate any comments you may have on the new PR.

**Comment by Demopans** [comment]
All right. I'll be closing this PR for the time being

**Pull request closed without merging**
